SELECT 
        A.AUTHOR_ID,
        A.AUTHOR_NAME,
        B.CATEGORY,
        SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
    FROM 
        BOOK B
        INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
        INNER JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE DATE_FORMAT(BS.SALES_DATE, "%Y-%m") = "2022-01"
GROUP BY 1, 3
ORDER BY 1, 3 DESC