# 2022년 11월 1일부터 2022년 11월 30일 사이에 하루라도 대여 예정되어 있는 차들
WITH PLANNED_CARS AS (
    SELECT
        CAR_ID
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE
        START_DATE <= '2022-11-30'
        AND END_DATE >= '2022-11-01'
),
DISCOUNT_INFO AS (
    SELECT
        CAR_TYPE,
        DISCOUNT_RATE
    FROM 
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE
        DURATION_TYPE = '30일 이상'
)

SELECT *
FROM (
    SELECT
        DISTINCT CAR_INFO.CAR_ID,
        CAR_INFO.CAR_TYPE,
        FLOOR(CAR_INFO.DAILY_FEE * (1 - DISCOUNT_INFO.DISCOUNT_RATE / 100) * 30) AS FEE
    FROM
        CAR_RENTAL_COMPANY_CAR AS CAR_INFO
            INNER JOIN DISCOUNT_INFO ON CAR_INFO.CAR_TYPE = DISCOUNT_INFO.CAR_TYPE
    WHERE
        CAR_ID NOT IN (SELECT CAR_ID FROM PLANNED_CARS)
        AND CAR_INFO.CAR_TYPE IN ('세단', 'SUV')
) FEE_TABLE
WHERE
    FEE BETWEEN 500000 AND 2000000
ORDER BY
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC


    

# SELECT
#     CAR_ID,
#     CAR_TYPE,
#     FEE
# FROM
#     CAR_RENTAL_COMPANY_CAR AS CAR_INFO
#         INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DISCOUNT_PLAN ON CAR_INFO.CAR_TYPE = DISCOUNT_PLAN.CAR_TYPE
# WHERE
#     CAR_ID NOT IN (SELECT CAR_ID FROM PLANNED_CARS)
#     AND CAR_TYPE IN ('세단', 'SUV')
# ORDER BY 
#     CAR_ID
