SELECT
    RI.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE,
    RI.FAVORITES,
    RI.ADDRESS,
    ROUND(AVG(RR.REVIEW_SCORE), 2)
FROM
    REST_INFO RI
    INNER JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
WHERE SUBSTR(RI.ADDRESS, 1, 2) = "서울"
GROUP BY RI.REST_ID
ORDER BY 6 DESC, RI.FAVORITES DESC