WITH HISTORY AS (
    SELECT
        HISTORY_ID,
        CAR_ID,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) >= 90 THEN "90일 이상"
            WHEN DATEDIFF(END_DATE, START_DATE) >= 30 THEN "30일 이상"
            WHEN DATEDIFF(END_DATE, START_DATE) >= 7 THEN "7일 이상"
            ELSE "해당 없음" 
        END AS DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY H
),
DISCOUNT AS (
    SELECT
        CAR_TYPE,
        DURATION_TYPE,
        DISCOUNT_RATE
    FROM
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    WHERE
        CAR_TYPE = "트럭"
)

SELECT 
    H.HISTORY_ID,
    IF(
        H.DURATION_TYPE = "해당 없음",
        FLOOR(C.DAILY_FEE * H.DURATION),
        FLOOR(C.DAILY_FEE * H.DURATION * (1 - D.DISCOUNT_RATE * 0.01))
    ) AS FEE
FROM 
    HISTORY H
    LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    LEFT JOIN DISCOUNT D ON H.DURATION_TYPE = D.DURATION_TYPE
WHERE
    C.CAR_TYPE = "트럭"
ORDER BY
    FEE DESC,
    H.HISTORY_ID DESC
