WITH TBL AS (
    SELECT 
        FH.FLAVOR,
        SUM(FH.TOTAL_ORDER) OVER (PARTITION BY FH.FLAVOR) +
        SUM(J.TOTAL_ORDER) OVER (PARTITION BY J.FLAVOR) AS TOTAL_ORDERS
    FROM FIRST_HALF FH
        LEFT JOIN JULY J ON FH.FLAVOR = J.FLAVOR
)

SELECT DISTINCT FLAVOR
FROM TBL T
ORDER BY T.TOTAL_ORDERS DESC
LIMIT 3
