WITH TBL AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY 1
    ORDER BY COUNT(*) DESC
    LIMIT 1
)

SELECT
    PROFILE.MEMBER_NAME,
    REVIEW.REVIEW_TEXT,
    DATE_FORMAT(REVIEW.REVIEW_DATE, "%Y-%m-%d")
FROM
    MEMBER_PROFILE PROFILE
    INNER JOIN REST_REVIEW REVIEW ON PROFILE.MEMBER_ID = REVIEW.MEMBER_ID
WHERE
    PROFILE.MEMBER_ID IN (SELECT MEMBER_ID FROM TBL)
ORDER BY 
    REVIEW.REVIEW_DATE ASC,
    REVIEW.REVIEW_TEXT ASC