WITH TBL AS (
    SELECT 
        FLAVOR,
        SUM(TOTAL_ORDER) OVER (PARTITION BY FLAVOR) AS TOTAL_ORDERS
    FROM FIRST_HALF
)

SELECT T.FLAVOR
FROM TBL T
LEFT JOIN ICECREAM_INFO II ON T.FLAVOR = II.FLAVOR
WHERE 
    II.INGREDIENT_TYPE = "fruit_based" AND 
    T.TOTAL_ORDERS > 3000
